### ISSUE TITLE
No releases?

### ISSUE THREAD

**Issue by dutsmiller** [jamesmcdonald/puppet-cpanm#2]
Out of curiosity, what happened to all of your release tags?  Our Puppetfile no longer works with this repo without explicitly pointing to this git-repo rather than using the puppetforge syntax.

**Comment by jamesmcdonald** [comment]
The releases are just on the forge, based on whatever's in the metadata.json at the time. I did push an update to puppetforge (0.9.5) with your change and a new dependency on stdlib. What error are you seeing?

**Comment by jamesmcdonald** [comment]
I added tags for what's in the two most recent versions on puppetforge in case you want to compare. There is also a workaround for a locale bug that I hadn't released, but it shouldn't cause problems.

**Comment by jamesmcdonald** [comment]
I'm closing this issue as I believe it should work (and there are now funky release tags and a changelog). Please let me know if you're still having problems.
