### ISSUE TITLE
Module Inline:C is continuously installed

### ISSUE THREAD

**Issue by mricon** [jamesmcdonald/puppet-cpanm#3]
It looks like obtaining the Inline::C::VERSION is problematic because the module complains about being used directly. Not sure what the solution here is, but right now it's installed on every puppet run, which is noisy, but benign.

**Comment by jamesmcdonald** [comment]
I was testing the package was available with `-M` rather than `-m`, so it was trying to run the module's import. I've fixed it and pushed version 0.9.6 to the forge. Let me know if that fixes the problem.
