### ISSUE TITLE
boolean check doesn't work in the latest puppet

### ISSUE THREAD

**Issue by martindemello** [jamesmcdonald/puppet-cpanm#8]
In order to get the module working in puppet 5.5, I had to change the checks to:

```
-    if @resource[:force] == :true
+    if @resource[:force] == true
       options << "-f"
     end
 
-    if @resource[:test] == :false
+    if @resource[:test] == false
       options << "-n"
     end
```

Not sure what the best way to fix it in a backward compatible manner would be - perhaps just `if @resource[:force] == :true || @resource[:force] == true`?

**Comment by jamesmcdonald** [comment]
Version 0.9.11 pushed with this fix.
